# Generated by Django 4.1.10 on 2024-02-24 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoLabelingConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("model_attrs", models.JSONField(default=dict)),
                ("template", models.TextField(default="")),
                ("label_mapping", models.JSONField(blank=True, default=dict)),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("Category", "category"),
                            ("Span", "span"),
                            ("Text", "text"),
                            ("Relation", "relation"),
                        ],
                        max_length=100,
                    ),
                ),
                ("default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_labeling_config",
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
