# Generated by Django 4.1.10 on 2024-02-27 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        ("utils", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="example",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="utils",
                to="projects.project",
            ),
        ),
    ]
