# Generated by Django 4.2.10 on 2024-03-07 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        ("utils", "0002_alter_example_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="example",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="examples",
                to="projects.project",
            ),
        ),
    ]
