# Generated by Django 4.1.10 on 2024-02-24 14:00

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("labels", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportedBoundingBox",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("labels.boundingbox",),
        ),
        migrations.CreateModel(
            name="ExportedCategory",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("labels.category",),
        ),
    ]
