# Generated by Django 4.1.10 on 2024-02-24 14:00

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("utils", "0001_initial"),
        ("labels", "0001_initial"),
        ("data_export", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportedComment",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("utils.comment",),
        ),
        migrations.CreateModel(
            name="ExportedExample",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("utils.example",),
        ),
        migrations.CreateModel(
            name="ExportedRelation",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("labels.relation",),
        ),
        migrations.CreateModel(
            name="ExportedSegmentation",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("labels.segmentation",),
        ),
        migrations.CreateModel(
            name="ExportedSpan",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("labels.span",),
        ),
        migrations.CreateModel(
            name="ExportedText",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("labels.textlabel",),
        ),
    ]
